FROM alpine:3

# fix verstions
ENV NGINX_VERSION=1.20.2-r1
ENV FFMPEG_VERSION=4.4.1-r2
ENV S3FS_VERSION=1.91-r0

# s3fs options
ENV S3_MOUNTPOINT="/opt/data"

RUN apk --no-cache add ffmpeg=${FFMPEG_VERSION} \
  nginx=${NGINX_VERSION} \
  s3fs-fuse=${S3FS_VERSION} --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

COPY nginx.conf /etc/nginx/nginx.conf

RUN adduser -D -g 'www' www
RUN mkdir -p ${S3_MOUNTPOINT} && chown -R www:www ${S3_MOUNTPOINT}

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

EXPOSE 1935
EXPOSE 80

CMD ["/docker-entrypoint.sh"]
